DROP DATABASE IF EXISTS PianoStore;
CREATE DATABASE PianoStore;

USE PianoStore;

DROP TABLE IF EXISTS Piano;
CREATE TABLE Piano (
	`id` INT NOT NULL AUTO_INCREMENT,
    `brand` VARCHAR(20) NOT NULL,
    `model` VARCHAR(20) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `description` VARCHAR(1000) NOT NULL,
    `price` VARCHAR(50) NOT NULL,
    `image` VARCHAR(50),
    PRIMARY KEY(`id`)
);

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	`id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) UNIQUE NOT NULL,
    `first_name` VARCHAR(50) NOT NULL,
    `last_name` VARCHAR(50) NOT NULL,
    `password` LONGTEXT NOT NULL,
    `position` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`)
);

INSERT INTO Users VALUES (1, 'mflood', 'Mark', 'Flood', 'password', 'admin');

INSERT INTO Piano VALUES (1, 'Boston', 'GP156', 'Grand', 'Boston GP156 - The Boston grand piano offers a larger soundboard in comparison to other pianos of the same length, due to its innovative “wide tail” design. This wider construction of the case means that a 5’ 10” Boston grand has the same soundboard area as a typical 6’ 2” grand piano, creating the power, richness, and feel of playing a much larger piano.', '€22,791', 'boston-GP156.jpg');
INSERT INTO Piano VALUES (2, 'Boston', 'GP163', 'Grand', 'Boston GP163 - The Boston grand piano offers a larger soundboard in comparison to other pianos of the same length, due to its innovative “wide tail” design. This wider construction of the case means that a 5’ 10” Boston grand has the same soundboard area as a typical 6’ 2” grand piano, creating the power, richness, and feel of playing a much larger piano.', '€25,902', 'boston-GP163.jpg');
INSERT INTO Piano VALUES (3, 'Boston', 'GP178', 'Grand', 'Boston GP178 - The Boston grand piano offers a larger soundboard in comparison to other pianos of the same length, due to its innovative “wide tail” design. This wider construction of the case means that a 5’ 10” Boston grand has the same soundboard area as a typical 6’ 2” grand piano, creating the power, richness, and feel of playing a much larger piano.', '€30,195', 'boston-GP178.jpg');
INSERT INTO Piano VALUES (4, 'Boston', 'GP193', 'Grand', 'Boston GP193 - The Boston grand piano offers a larger soundboard in comparison to other pianos of the same length, due to its innovative “wide tail” design. This wider construction of the case means that a 5’ 10” Boston grand has the same soundboard area as a typical 6’ 2” grand piano, creating the power, richness, and feel of playing a much larger piano.', '€36,285', 'boston-GP193.jpg');
INSERT INTO Piano VALUES (5, 'Boston', 'GP215', 'Grand', 'Boston GP215 - The Boston grand piano offers a larger soundboard in comparison to other pianos of the same length, due to its innovative “wide tail” design. This wider construction of the case means that a 5’ 10” Boston grand has the same soundboard area as a typical 6’ 2” grand piano, creating the power, richness, and feel of playing a much larger piano.', '€43,616', 'boston-GP193.jpg');
INSERT INTO Piano VALUES (6, 'Essex', 'EGP 155C', 'Grand', 'Designed by Steinway & Sons in collaboration with renowned furniture designer William Faber, the Essex has been created as a tribute to the idea that beautiful piano styles and finishes can and should be possible in every price range. With elegant traditional styling and museum-quality finishes, Essex will be a stunning addition to your home.', '€16,300', 'essex-EGP.jpg');
INSERT INTO Piano VALUES (7, 'Kawai', 'GL10', 'Grand', "The new GL Series Grand Pianos possess all the essential qualities that have made Kawai pianos a preferred choice of pianists and educators for generations.", '€10,526', 'kawai-GL10.jpg');
INSERT INTO Piano VALUES (8, 'Kawai', 'GL30', 'Grand', 'The new Kawai GL30 - conceived with one goal in mind—to provide exceptional touch and tone that endures.', '€15,178', 'kawai-GL30.jpg');
INSERT INTO Piano VALUES (9, 'Kawai', 'GL50', 'Grand', 'The new Kawai GL50 Grand Piano possess all the essential qualities that have made Kawai pianos a preferred choice of pianists and educators for generations. Conceived with one goal in mind—to provide exceptional touch and tone that endures.', '€24.310', 'kawai-GL50.jpg');
INSERT INTO Piano VALUES (10, 'Kawai', 'GM10', 'Grand', '', '€10,795', 'kawai-GM10.jpg');
INSERT INTO Piano VALUES (11, 'Kawai', 'GX1', 'Grand', 'The GX-1 offers a level of elegance and craftsmanship that is unsurpassed for a piano of its size. The new standard of grand piano design is beyond imagination.', '€20.739', 'kawai-GX1.jpg');
INSERT INTO Piano VALUES (12, 'Kawai', 'GX2', 'Grand', 'The GX-2 is one of the world’s best-selling grand pianos offering superb tonal depth and resonance, and a classic size to grace any home, studio or performance venue. The new standard of grand piano design is beyond imagination.', '€22,143', 'kawai-GX2.jpg');
INSERT INTO Piano VALUES (13, 'Kawai', 'GX3', 'Grand', 'GX3 impresses with a dignified elegance and distinct tone evoking the qualities of a much larger grand. With outstanding tone and touch in a versatile size, it is a preferred choice of professionals.', '€28,040', 'kawai-GX3.jpg');
INSERT INTO Piano VALUES (14, 'Kawai', 'GX5', 'Grand', 'The GX-5 is the artist’s “grand for all seasons”. With resplendent tone and superb power, it adapts to an exceptional range of musical requirements and performance venues.', '€33,643', 'kawai-GX5.jpg'); 
INSERT INTO Piano VALUES (15, 'Kawai', 'GX6', 'Grand', 'GX6 combines exquisite tone with stunning beauty to offer an instrument befitting the finest concert hall or professional studio. The new standard of grand piano design is beyond imagination.', '€37,567', 'kawai-GX6.jpg');
INSERT INTO Piano VALUES (16, 'Kawai', 'GX7', 'Grand', 'GX7 Piano. At the lofty pinnacle of the GX Series, the regal GX-7 speaks with the transcendent character and authority that has made it the definitive choice of the consummate professional. The new standard of grand piano design is beyond imagination.', '€42,478', 'kawai-GX7.jpg');
INSERT INTO Piano VALUES (17, 'Kawai', 'Shigeru SK2L', 'Grand', "Shigeru SK2L. 5ft11in. Ebony Polished The Shigeru Kawai Piano... a spiritual union of man, nature and art... a union derived from the innate and inexorable desire for harmony.", '€33,531', 'kawai-SK2L.jpg'); 
INSERT INTO Piano VALUES (18, 'Kawai', 'Shigeru SK3L', 'Grand', "Shigeru SK2L. 5ft11in. Ebony Polished The Shigeru Kawai Piano... a spiritual union of man, nature and art... a union derived from the innate and inexorable desire for harmony.", '€43,064', 'kawai-SK3L.jpg');
INSERT INTO Piano VALUES (19, 'Kawai', 'Shigeru SK5L', 'Grand', "Kawai Shigeru SK5L. 6ft6in. Ebony Polished. The Shigeru Kawai Piano... a spiritual union of man, nature and art... a union derived from the innate and inexorable desire for harmony. Of all the musical masterpieces that come forth from Kawai, fewer than one in one hundred will bear the name SHIGERU.", '€49,058', 'kawai-SK5L.jpg');
INSERT INTO Piano VALUES (20, 'Kawai', 'Shigeru SK6L', 'Grand', "SK6L - 7' Polished Ebony. The Shigeru Kawai Piano... a spiritual union of man, nature and art... a union derived from the innate and inexorable desire for harmony.", '€56,446', 'kawai-SK6L.jpg');
INSERT INTO Piano VALUES (21, 'Kawai', 'Shigeru SK7L', 'Grand', "Shigeru SK7L. 7ft6in. Polished Ebony. The Shigeru Kawai Piano... a spiritual union of man, nature and art... a union derived from the innate and inexorable desire for harmony. Of all the musical masterpieces that come forth from Kawai, fewer than one in one hundred will bear the name SHIGERU.", '€63,421', 'kawai-SK7L.jpg');
INSERT INTO Piano VALUES (22, 'Steinway & Sons', 'Model A', 'Grand', "Steinway&Sons Model 'A' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelA.jpg');
INSERT INTO Piano VALUES (23, 'Steinway & Sons', 'Model B', 'Grand', "Steinway&Sons Model 'B' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelB.jpg');
INSERT INTO Piano VALUES (24, 'Steinway & Sons', 'Model C', 'Grand', "Steinway&Sons Model 'C' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelC.jpg');
INSERT INTO Piano VALUES (25, 'Steinway & Sons', 'Model D', 'Grand', "Steinway&Sons Model 'D' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelD.jpg');
INSERT INTO Piano VALUES (26, 'Steinway & Sons', 'Model M', 'Grand', "Steinway&Sons Model 'M' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelM.jpg');
INSERT INTO Piano VALUES (27, 'Steinway & Sons', 'Model O', 'Grand', "Steinway&Sons Model 'O' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelS.jpg');
INSERT INTO Piano VALUES (28, 'Steinway & Sons', 'Model S', 'Grand', "Steinway&Sons Model 'S' - Every Steinway piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.", 'Price on Application', 'S&S-modelS.jpg');
INSERT INTO Piano VALUES (29, 'Yamaha', 'C1X', 'Grand', "Yamaha C1X - 5ft3in. Polished Ebony. The legacy of the CFX continues Preserving tradition is not the same thing as refusing to change;rather, it is from the ongoing search for perfection that traditions emerge.", '€21,708', 'yamaha-C1X.jpg');
INSERT INTO Piano VALUES (30, 'Yamaha', 'C2X', 'Grand', "Yamaha C2X - 5ft8in. Ebony Polished. The legacy of the CFX continues Preserving tradition is not the same thing as refusing to change;rather, it is from the ongoing search for perfection that traditions emerge.", '€23,671', 'yamaha-C2X.jpg');
INSERT INTO Piano VALUES (31, 'Yamaha', 'C3X', 'Grand', "Yamaha C3X. The legacy of the CFX continues Preserving tradition is not the same thing as refusing to change;rather, it is from the ongoing search for perfection that traditions emerge.", '€28,824', 'yamaha-C3X.jpg');
INSERT INTO Piano VALUES (32, 'Yamaha', 'C5X', 'Grand', "Yamaha C5X. 6ft7in. Ebony Polish. The legacy of the CFX continues Preserving tradition is not the same thing as refusing to change;rather, it is from the ongoing search for perfection that traditions emerge.", '€35,684', 'yamaha-C5X.jpg');
INSERT INTO Piano VALUES (33, 'Yamaha', 'C6X', 'Grand', "Yamaha C6X. The legacy of the CFX continues Preserving tradition is not the same thing as refusing to change;rather, it is from the ongoing search for perfection that traditions emerge.", '€39,757', 'yamaha-C6X.jpg');
INSERT INTO Piano VALUES (34, 'Yamaha', 'C7X', 'Grand', "Yamaha C7X. 7ft6in. Ebony Polish. The legacy of the CFX continues Preserving tradition is not the same thing as refusing to change;rather, it is from the ongoing search for perfection that traditions emerge.", '€45,869', 'yamaha-C7X.jpg');
INSERT INTO Piano VALUES (35, 'Yamaha', 'CFIIIS', 'Grand', "Yamaha CFIIISA new standard of excellence for the concert pianistUltimate example of a proud piano heritage, the CFIIIS concert grand is prized by performers and performing arts centres around the world.", 'Price on Application', 'yamaha-CFIIIS.jpg');
INSERT INTO Piano VALUES (36, 'Yamaha', 'GB1', 'Grand', "Yamaha GB1. The Most Affordable Yamaha Grand Piano Ever – The new GB1! Now you can own the grand piano you've always wanted, even if space and budget are limited. Uncommonly compact, the GB1 is right at home in smaller rooms, while offering all the power, tonality and expressive range of a classic Yamaha Grand Piano.", '€10,287', 'yamaha-GB1.jpg');
INSERT INTO Piano VALUES (37, 'Yamaha', 'GC1', 'Grand', "Yamaha GC1. 5ft3in. Polished Ebony With a full, resonant tone that only a grand piano can possess, the GC1 series provides superior performance at an affordable price.", '€16,768', 'yamaha-GC1.jpg');
INSERT INTO Piano VALUES (38, 'Yamaha', 'GC2', 'Grand', "5ft8in Ebony Polished The beautiful new GC2 combines the duplex scaling and rich tonal character of the Conservatoire C2 grand with cost-saving advantages in materials and production to create an instrument that's both exceptionally expressive and uncommonly affordable.", '€19,077', 'yamaha-GC2.jpg');
INSERT INTO Piano VALUES (39, 'Yamaha', 'S4', 'Grand', "Yamaha S4, Superbly hand crafted instruments of singular eloquence. Individually assembled in the Yamaha concert grand workshop. Yamaha S4 grand piano is conceived and crafted to gratify the most discerning professionals.", 'Price on Application', 'yamaha-S4.jpg');
INSERT INTO Piano VALUES (40, 'Yamaha', 'S6', 'Grand', "Yamaha S6, Superbly hand crafted instruments of singular eloquence. Individually assembled in the Yamaha concert grand workshop. Yamaha S6 grand piano is conceived and crafted to gratify the most discerning professionals.", 'Price on Application', 'yamaha-S6.jpg');
INSERT INTO Piano VALUES (41, 'Boston', 'UP118', 'Upright', 'Boston UP118 Piano. EXCELLENCE: To some it is only a word. For the Boston it is a standard. No piano in modern history has ever made itself heard so immediately or so dramatically as has the Boston.', '€10,332', 'boston-UP118.jpg');
INSERT INTO Piano VALUES (42, 'Boston', 'UP126', 'Upright', 'Boston UP126 Piano. EXCELLENCE: To some it is only a word. For the Boston it is a standard. No piano in modern history has ever made itself heard so immediately or so dramatically as has the Boston.', '€11,672', 'boston-UP126.jpg');
INSERT INTO Piano VALUES (43, 'Boston', 'UP132', 'Upright', 'Boston UP132 Piano. EXCELLENCE: To some it is only a word. For the Boston it is a standard. No piano in modern history has ever made itself heard so immediately or so dramatically as has the Boston.', '€12,767', 'boston-UP132.jpg');
INSERT INTO Piano VALUES (44, 'Kawai', 'K15', 'Upright', "The Kawai wood technology uses all of senses ... seeing, smelling, feeling, to select the best woods. The soundboards of the K-series are finished of massive, very straight-grained spruce, that is very carefully selected, asymmetrical vaulted and scientifically tested, to fulfil Kawai's high demands to te resonance behaviour and to the best sound.", '€3,832', 'kawai-K15.jpg');
INSERT INTO Piano VALUES (45, 'Kawai', 'K200', 'Upright', 'With outstanding tone and touch, the K 200 offers the dependebality and character needed to please any performing pianist from the novice to the seasoned professional.', '€5,078', 'kawai-K200.jpg');
INSERT INTO Piano VALUES (46, 'Kawai', 'K300', 'Upright', 'The K-300 builds upon the success of its awardwinning predecessor, the K-3, that was named Acoustic Piano of the Year in four consecutive years. The K-300 proudly extends this distinguished legacy.', '€6,464', 'kawai-K300.jpg');
INSERT INTO Piano VALUES (47, 'Kawai', 'K500', 'Upright', 'The K Series upright pianos offer a level of tone quality and performance that rivals many grand pianos. With sturdy construction for years of reliable service, the K Series models are excellent for auditoriums, schools and other institutional settings.', '€9,035', 'kawai-K500.jpg');
INSERT INTO Piano VALUES (48, 'Kawai', 'K600', 'Upright', 'The K-600 offer a level of tone quality and performance that may rival many grand pianos. With sturdy construction for years of reliable service, the K-600 is excellent for auditoriums, schools and other institutional settings.', '€10,323', 'kawai-K600.jpg');
INSERT INTO Piano VALUES (49, 'Kawai', 'K800', 'Upright', 'The K-800 is the epitome of upright piano craftsmanship. Its elegant form and exceptional tone will fulfill the needs of any professional teaching studio or intimate performance setting.', '€12,648', 'kawai-K800.jpg');
INSERT INTO Piano VALUES (50, 'Steinway & Sons', 'Model K', 'Upright', 'Steinway&Sons Model K. Every Steinway&Sons piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.', 'Prices on Application', 'S&S-modelK.jpg');
INSERT INTO Piano VALUES (51, 'Steinway & Sons', 'Model V', 'Upright', 'Steinway&Sons Model V. Every Steinway&Sons piano has its own distinctive character, created by the combination of superior design and materials with fine hand craftsmanship.', 'Prices on Application', 'S&S-modelV.jpg');
INSERT INTO Piano VALUES (52, 'Yamaha', 'B1', 'Upright', "Yamaha B1 - Exemplifying Yamaha's well-established design principles, the B1 redefines the word value. Whilst retaining Yamaha standards in every way, B1 offers the joy of Yamaha ownership at a price that will astonish and delight. B-SERIES. B for BEAUTIFUL PIANOS.", '€3,423', 'yamaha-B1.jpg');
INSERT INTO Piano VALUES (53, 'Yamaha', 'B2', 'Upright', 'Yamaha B2 With its larger dimensions and heavier construction, the new B2 delivers a superior sound through added depth and volume. Front and rear castors enhance movability while the elegantly detailed, traditional cabinetry ensures that the B2 looks right at home in your living space.', '€4,717', 'yamaha-B2.jpg');
INSERT INTO Piano VALUES (54, 'Yamaha', 'B3', 'Upright', 'Yamaha B2 With its larger dimensions and heavier construction, the new B2 delivers a superior sound through added depth and volume. Front and rear castors enhance movability while the elegantly detailed, traditional cabinetry ensures that the B2 looks right at home in your living space.', '€5,527', 'yamaha-B3.jpg');
INSERT INTO Piano VALUES (55, 'Yamaha', 'P116', 'Upright', 'Yamaha P116 The medium-sized piano with the grown-up sound Although it is "just" 116cm tall, the P116 has an astonishing sound potential, which will be hard to be matched by another piano in this class.', '€6,670', 'yamaha-P116.jpg');
INSERT INTO Piano VALUES (56, 'Yamaha', 'P121', 'Upright', 'Designed in Europe to European preferences, the Yamaha P121 boasts exquisite cabinetry, European spruce soundboard and back posts, and the rich, expressive voice of a full-sized upright. Also available as a Silent model.', '€7,522', 'yamaha-P121.jpg');
INSERT INTO Piano VALUES (57, 'Yamaha', 'SE122', 'Upright', 'Yamaha SE 122 In a unique collaboration between East and West, SE Series combines the meticulous precision for which Yamaha is renowned with the inspiration and warmth of Europe’s rich musical heritage.', '€15,834', 'yamaha-SE122.jpg');
INSERT INTO Piano VALUES (58, 'Yamaha', 'SE132', 'Upright', 'Yamaha SE 132 In a unique collaboration between East and West, SE Series combines the meticulous precision for which Yamaha is renowned with the inspiration and warmth of Europe’s rich musical heritage.', '€19,044', 'yamaha-SE132.jpg');
INSERT INTO Piano VALUES (59, 'Yamaha', 'SU118', 'Upright', 'Yamaha SU118 Individually handcrafted from select materials by elite Yamaha artisans, the Yamaha SU118 piano can convey every nuance of emotion.', '€14,472', 'yamaha-SU118.jpg');
INSERT INTO Piano VALUES (60, 'Yamaha', 'SU7', 'Upright', 'Yamaha SU7 The new flagship of Yamaha’s upright series – The concert upright SU7 The SU-series upright pianos are made on an own production site, where the finest craftsmen and technicians are dedicated to these instruments and their special production.', '€24,291', 'yamaha-SU7.jpg');
INSERT INTO Piano VALUES (61, 'Yamaha', 'U1', 'Upright', 'Yamaha U1 A perennial favourite among discerning pianists, the Yamaha U1 offers outstanding musical performance, setting the standards by which many other upright pianos are measured.', '€9,615', 'yamaha-U1.jpg');
INSERT INTO Piano VALUES (62, 'Yamaha', 'U3', 'Upright', 'Yamaha U3 An expansive soundboard and acoustic chamber give the 131 cm U3 extended power and projection, with the peerless tonal and expressive control of the legendary Yamaha action.', '€11,420', 'yamaha-U3.jpg');
INSERT INTO Piano VALUES (63, 'Yamaha', 'YUS1', 'Upright', 'Yamaha YUS1 Best design and technology for ultimate performance Yamaha U-Series upright pianos have long been a leading choice for educational institutions, professional musicians and discriminating home pianists.', '€11,166', 'yamaha-YUS1.jpg');
INSERT INTO Piano VALUES (64, 'Yamaha', 'YUS3', 'Upright', 'With YUS Series Yamaha takes quality and performance of professional upright piano series to a new level. Best design and technology for ultimate performance Yamaha U-Series upright pianos have long been a leading choice for educational institutions, professional musicians and discriminating home pianists.', '€13,112', 'yamaha-YUS3.jpg');
INSERT INTO Piano VALUES (65, 'Yamaha', 'YUS5', 'Upright', 'Yamaha YUS5 Best design and technology for ultimate performance Yamaha U-Series upright pianos have long been a leading choice for educational institutions, professional musicians and discriminating home pianists.', '€14,286', 'yamaha-YUS5.jpg');
INSERT INTO Piano VALUES (66, 'Kawai', 'CA48', 'Digital', "Concert Grand Touch & Tone, Concert Artist Affordability! Featuring Kawai's highly regarded RM3 Grand wooden-key keyboard action, and stunning Progressive Harmonic Imaging sound technology, the new CA13 offers an excellent introduction to Concert Artist quality at an attractive price.", '€1,933', 'kawai-CA48.jpg');
INSERT INTO Piano VALUES (67, 'Kawai', 'CA58', 'Digital', 'The Concert Grand experience in the comfort of your home Kawai has been crafting musical instruments for 85 years, maintaining traditional processes while embracing original ideas.', '€2,628', 'kawai-CA58.jpg');
INSERT INTO Piano VALUES (68, 'Kawai', 'CA78', 'Digital', 'Kawai CA78 - Stunning multi-channel grand piano sounds, an ultra-realistic wooden-key keyboard action, premium audio, amplification, and speaker technologies, convenient Bluetooth connectivity, and a modern touchscreen interface', '€2,994', 'kawai-CA78.jpg');
INSERT INTO Piano VALUES (69, 'Kawai', 'CA98', 'Digital', 'Kawai CA98 - The Concert Grand experience in the comfort of your home Kawai has been crafting musical instruments for 85 years, maintaining traditional processes while embracing original ideas.', '€3,702', 'kawai-CA98.jpg');
INSERT INTO Piano VALUES (70, 'Kawai', 'CN27', 'Digital', 'Authentic Touch, Beautiful Sound, Inspiring Features, Renowned Quality! The new standard in digital piano value and performance. Kawai’s latest CN Series model CN25 features a realistic, 88-note keyboard, beautiful grand piano sounds', '€1,421', 'kawai-CN27.jpg');
INSERT INTO Piano VALUES (71, 'Kawai', 'CN37', 'Digital', 'Kawai CN37 - ‘Responsive Hammer III’weighted-key action, with Ivory Touch key surfaces and Let-off simulation. The new Responsive Hammer III (RHIII) action recreates the distinctive touch of an acoustic grand piano.', '€1,741', 'kawai-CN37.jpg');
INSERT INTO Piano VALUES (72, 'Kawai', 'CS11', 'Digital', 'Kawai CS11 - Luxurious appearance, stunning sound, impeccable touch: The new range of Classic Series luxury digital pianos – crafted by Japan’s premier acoustic piano company.', '€4,213', 'kawai-CS11.jpg');
INSERT INTO Piano VALUES (73, 'Kawai', 'CS8', 'Digital', 'Kawai CS8 - Luxurious appearance, stunning sound, impeccable touch: The new range of Classic Series luxury digital pianos – crafted by Japan’s premier acoustic piano company.', '€3,016', 'kawai-CS8.jpg');
INSERT INTO Piano VALUES (74, 'Kawai', 'ES8', 'Digital', 'The ES8’s class-leading Responsive Hammer II keyboard action recreates the supreme touch of an acoustic grand piano, with its realistic movement and rigid, springless design providing a smooth and natural piano playing experience.', '€1,610', 'kawai-ES8.jpg');
INSERT INTO Piano VALUES (75, 'Kawai', 'MP11SE', 'Digital', 'The most authentic keyboard, the most realistic sound, and the most articulate control. While others may claim to be ‘the best’, only one can be considered the most genuine. Kawai MP11SE – the stage piano for music professionals who do not accept compromise.', '€2,423', 'kawai-MP11SE.jpg');
INSERT INTO Piano VALUES (76, 'Kawai', 'MP7SE', 'Digital', 'The All-In-One stage piano The MP7SE is the ultimate stage piano for performing musicians. The MP7SE delivers the incredible sound quality of its bigger brother MP11SE in a more compact, portable package.', '€1,732', 'kawai-MP7SE.jpg');
INSERT INTO Piano VALUES (77, 'Roland', 'DP603', 'Digital', "Roland DP603—a new digital piano whose stylish cabinet and minimalist design are the perfect match for your modern living space. The DP603’s appeal is more than skin-deep, with Roland’s latest SuperNATURAL Piano Modeling for rich, authentic sounds and a PHA-50 keyboard that feels so expressive to play.", '€1,999', 'roland-DP603.jpg');
INSERT INTO Piano VALUES (78, 'Roland', 'F140', 'Digital', 'Roland F140 - Premium Piano Performance for Compact Living Spaces If you live in an apartment or condo and want to bring a quality piano into your life, the F-140 is for you.', '€1,023', 'roland-F140.jpg');
INSERT INTO Piano VALUES (79, 'Roland', 'FP60', 'Digital', "", '€1,469', 'roland-FP60.jpg');
INSERT INTO Piano VALUES (80, 'Roland', 'FP90', 'Digital', "Roland FP90 - Roland’s Premier Technologies for an Authentic Piano Experience at Home The stylish and sophisticated FP-90 is the ideal choice for piano enjoyment in modern living spaces, offering tone, touch, and expressiveness to satisfy even the most demanding players.", '€1,889', 'roland-FP90.jpg');
INSERT INTO Piano VALUES (81, 'Roland', 'GP607 PE', 'Digital', 'GP607 PE - A mini grand piano that sparks creativity and complements your living space.', '€4,999', 'roland-GP607PE.jpg');
INSERT INTO Piano VALUES (82, 'Roland', 'HP702', 'Digital', 'Uncompromising piano performance and style The affordable HP702 brings style and premium piano performance into your home. Practice at midnight, immersed in sound from the Headphones 3D Ambience feature. Wirelessly stream songs and app audio via Bluetooth or try the onboard tutorials and improve your playing skills. Whatever the musical scenario, the HP702 delivers a superior piano experience—for far less than you think.', '€1,699', 'roland-HP702.jpg');
INSERT INTO Piano VALUES (83, 'Roland', 'HP704', 'Digital', 'Premium look and authentic piano touch with four-speaker audio system The HP704 provides the style, performance, and pristine sound projection you’d expect from a premium studio piano. With its sleek, sophisticated cabinet design, this digital piano makes a statement wherever you play it—and a range of finishes ensures it fits in anywhere. The advanced PHA-50 keyboard, onboard tutorial features, and Bluetooth connectivity with music apps mean you’ll always be inspired to play, explore and improve. And the tall, elegant cabinet houses a powerful four-speaker audio system that delivers dynamic, room-filling sound as you perform—or while you relax by streaming your favorite tunes.', '€1,999', 'roland-HP704.jpg');
INSERT INTO Piano VALUES (84, 'Roland', 'HPi50E', 'Digital', 'The Piano That Teaches You How to Play It – While Having Fun.', '€2,613', 'roland-HPi50E.jpg');
INSERT INTO Piano VALUES (85, 'Roland', 'LX-705', 'Digital', 'Roland LX-705 - An Elegant, Sophisticated Home Piano with Truly Beautiful Sound.', '€2,399', 'roland-LX-705.jpg');
INSERT INTO Piano VALUES (86, 'Roland', 'LX-706', 'Digital', 'Roland LX-706 - An Elegant, Sophisticated Home Piano with Truly Beautiful Sound.', '€3,300', 'roland-LX-706.jpg');
INSERT INTO Piano VALUES (87, 'Roland', 'LX-708', 'Digital', 'Roland LX-708 - An Elegant, Sophisticated Home Piano with Truly Beautiful Sound.', '€3,999', 'roland-LX-708.jpg');
INSERT INTO Piano VALUES (88, 'Roland', 'RP501R', 'Digital', 'SuperNATURAL® Piano Experience a New Way to Play Features The RP-501R is an affordable and fun piano with first-class sounds, touch, and play-along rhythm accompaniment.', '€1,299', 'roland-RP501R.jpg');
INSERT INTO Piano VALUES (89, 'Yamaha', 'AvantGrand N1', 'Digital', 'Yamaha AvantGrand N1. The latest addition to the range, the N1 delivers the captivating sound of AvantGrand in its simplest form. In terms of playing feel and responsive action, the N1 is simply incredible, setting a new standard with its perfect integration of acoustic and digital technologies.', '€7,756', 'yamaha-AGN1.jpg');
INSERT INTO Piano VALUES (90, 'Yamaha', 'AvantGrand N2', 'Digital', 'Yamaha AvantGrand N2. Featuring the same grand piano action as the N3 in a form that sits beautifully to any wall, the N2 is an instrument for the future, yet one that holds firmly to its identity as a grand piano.', '€13,237', 'yamaha-AGN2.jpg');
INSERT INTO Piano VALUES (91, 'Yamaha', 'AvantGrand N3X', 'Digital', 'Yamaha AvantGrand N3X. Feel and experience a piano sound that you have never had before from this stunning and elegant instrument. In pursuit of the Grand Piano in everything such sound, touch and action.', '€20,371', 'yamaha-AGN3X.jpg');
INSERT INTO Piano VALUES (92, 'Yamaha', 'AvantGrand NU1X', 'Digital', 'Introducing the NU1X, a hybrid piano from Yamaha that combines the traditions of an acoustic instrument with the innovation of digital technology.', '€5,372', 'yamaha-AGNU1X.jpg');
INSERT INTO Piano VALUES (93, 'Yamaha', 'CLP-625', 'Digital', 'The Yamaha CLP Series next-generation digital piano. Sound source recorded from a world-class Yamaha full concert grand piano. With a beautiful appearance inspired by acoustic piano cabinetry, these are digital pianos that refine everything you want, to the highest level, for enjoyable piano performance.', '€1,551', 'yamaha-CLP-625.jpg');
INSERT INTO Piano VALUES (94, 'Yamaha', 'CLP-635', 'Digital', 'The Yamaha CLP-635 Series next-generation digital piano. Sound source recorded from a world-class Yamaha full concert grand piano. With a beautiful appearance inspired by acoustic piano cabinetry, these are digital pianos that refine everything you want, to the highest level, for enjoyable piano performance.', '€2,014', 'yamaha-CLP-635.jpg');
INSERT INTO Piano VALUES (95, 'Yamaha', 'CLP-645', 'Digital', 'The Yamaha CLP-645 Series next-generation digital piano. Sound source recorded from a world-class Yamaha full concert grand piano. With a beautiful appearance inspired by acoustic piano cabinetry, these are digital pianos that refine everything you want, to the highest level, for enjoyable piano performance.', '€2,696', 'yamaha-CLP-645.jpg');
INSERT INTO Piano VALUES (96, 'Yamaha', 'CLP-665GP', 'Digital', 'The Yamaha CLP-665GP - A Clavinova with grand design; sound and appearance that will add a touch of class to any environment.', '€4,914', 'yamaha-CLP-665GP.jpg');
INSERT INTO Piano VALUES (97, 'Yamaha', 'CLP-675', 'Digital', 'The Yamaha CLP-675 Series next-generation digital piano. Sound source recorded from a world-class Yamaha full concert grand piano. With a beautiful appearance inspired by acoustic piano cabinetry, these are digital pianos that refine everything you want, to the highest level, for enjoyable piano performance.', '€3,345', 'yamaha-CLP-675.jpg');
INSERT INTO Piano VALUES (98, 'Yamaha', 'CLP-685', 'Digital', 'The Yamaha CLP-685 Series next-generation digital piano. Sound source recorded from a world-class Yamaha full concert grand piano. With a beautiful appearance inspired by acoustic piano cabinetry, these are digital pianos that refine everything you want, to the highest level, for enjoyable piano performance.', '€4,651', 'yamaha-CLP-685.jpg');
INSERT INTO Piano VALUES (99, 'Yamaha', 'CVP-701', 'Digital', 'The Yamaha CVP-701 features an intuitive touch screen that takes you right to the heart of the instrument. From lifting the lid of a concert grand, placing it it different rooms and mixing the backing band, controlling the sounds and features of a CVP Clavinova has never been easier or more exciting!', '€3,312', 'yamaha-CVP-701.jpg');
INSERT INTO Piano VALUES (100, 'Yamaha', 'CVP-705', 'Digital', 'The Yamaha CVP-705 - Featuring the RGE Sound Engine for outstanding playing response and the GH3 (Graded Hammer 3) keyboard with synthetic ivory keytops for maximum playing comfort, the CVP-705 offers extremely high quality piano performance.', '€5,609', 'yamaha-CVP-705.jpg');
INSERT INTO Piano VALUES (101, 'Yamaha', 'CVP-709', 'Digital', 'The Yamaha CVP-709 - "Real Grand Expression" Sound, touch, pedals–perfectly integrated to give you the sensation of playing a grand piano.', '€8,997', 'yamaha-CVP-709.jpg');
INSERT INTO Piano VALUES (102, 'Yamaha', 'CVP-709GP', 'Digital', 'The Yamaha CVP-709GP - How could Yamaha improve the design of the ultimate Clavinova CVP-709 digital piano? Put it in a polished ebony grand piano cabinet.', '€13,781', 'yamaha-CVP-709GP.jpg');
INSERT INTO Piano VALUES (103, 'Yamaha', 'P255', 'Digital', 'Yamaha P255 contemporary digital piano is for all musicians looking for an instrument suitable for both serious practice and live performance.', '€1,544', 'yamaha-P255.jpg');

SELECT * FROM Piano;
SELECT * FROM Users;